plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - "app/views/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "db/schema.rb"
    - "db/*.rb"
    - "db/migrate/**/*"
    - "db/fixtures/poc/**/*"
    - "db/fixtures/production/**/*"
    - "db/fixtures/staging/**/*"
    - "log/**/*"
    - "node_modules/**/*"
    - "public/**/*"
    - "storage/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "server/**/*"

RSpec/ContextWording:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

